### ISSUE TITLE
New BBs indexed from 1

### ISSUE THREAD

**Issue by dimakbalazs** [bauerdavid/napari-nD-annotator#24]
Describe the bug
The new bbs will be index from 1 (version 0.0.6)

To Reproduce

    Open the Object List plugin
    Import a Bounding box layer (or create a new BoundingBox layer then import an old one)
    Create a new Bounding box
    The new BB's index will be 1

![kép](https://user-images.githubusercontent.com/107544739/174029778-994e2117-6dd8-4368-a08d-42f4fea11f69.png)

napari info:
napari: 0.4.15
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9664
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.15
- svg: 0.1.6

**Comment by bauerdavid** [comment]
fixed by 166d614 (will create a new release soon)
