### ISSUE TITLE
'autofill objects' mode ignores 'preserve labels'

### ISSUE THREAD

**Issue by niederle** [bauerdavid/napari-nD-annotator#28]
**Describe the bug**
I have 'autofill objects' activated as well as 'preserve labels' from the labeling GUI. If I draw next to an existing label, the label is preserved while drawing but the fill mode sometimes ignores it so that some already labeled pixels get relabeled.

**To Reproduce**
- 'autofill objects' activated 
- 'preserve labels' activated
- draw one labels (convex/concave shapes make the issue more obvious)
- draw another label next to it

**Expected behavior**
I would expect the existing label remains untouched.

**napari info**
```
napari: 0.4.15
Platform: macOS-10.13.6-x86_64-i386-64bit
System: MacOS 10.13.6
Python: 3.9.7 (default, Sep 16 2021, 08:50:36) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 INTEL-10.36.32
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1440x900, scale 2.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- animation: 0.0.2
- cellpose-napari: 0.1.4
- clEsperanto: 0.15.4
- console: 0.0.4
- devbio_napari: 0.4.0
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.6.6
- napari-brightness-contrast: 0.1.6
- napari-clusters-plotter: 0.2.2
- napari-crop: 0.1.5
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-itk-io: 0.1.0
- napari-ome-zarr: 0.3.2
- napari-plot-profile: 0.2.1
- napari-plugin-search: 0.1.3
- napari-segment-blobs-and-things-with-membranes: 0.2.17
- napari-simpleitk-image-processing: 0.2.1
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.10
- napari-workflow-optimizer: 0.1.3
- napari_skimage_regionprops1: 0.2.9
- napari_skimage_regionprops2: 0.2.9
- scikit-image: 0.4.15
- svg: 0.1.6
```

**Comment by bauerdavid** [comment]
problem resolved in 2b36d04 (luckily an easy fix). However, I will create a new release only later. If you want to try the new version, you can directly install it from the repository:
`pip install git+https://github.com/bauerdavid/napari-nD-annotator.git@main`
