### ISSUE TITLE
does not working

### ISSUE THREAD

**Issue by dimakbalazs** [bauerdavid/napari-nD-annotator#37]
**Describe the bug**
If I want start Annotation Toolbox & Object List it drops error.

**To Reproduce**
start napari-nd-annotator/object list

**Plugin error**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Programs\Python\Python39\lib\site-packages\npe2\_command_registry.py in resolve(self=CommandHandler(id='napari-nD-annotator.object_li..., python_name='napari_nd_annotator:ListWidgetBB'))
     29         try:
---> 30             self.function = import_python_name(self.python_name)
        self.function = None
        global import_python_name = 
        self.python_name = 'napari_nd_annotator:ListWidgetBB'
     31         except Exception as e:

~\AppData\Local\Programs\Python\Python39\lib\site-packages\npe2\manifest\utils.py in import_python_name(python_name='napari_nd_annotator:ListWidgetBB')
    166 
--> 167     mod = import_module(module_name)
        mod = undefined
        import_module = 
        module_name = 'napari_nd_annotator'
    168     return getattr(mod, funcname)

~\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py in import_module(name='napari_nd_annotator', package=None)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
        global _bootstrap._gcd_import = 
        name = 'napari_nd_annotator'
        level = 0
        package = None
    128 

~\AppData\Local\Programs\Python\Python39\lib\importlib\_bootstrap.py in _gcd_import(name='napari_nd_annotator', package=None, level=0)

~\AppData\Local\Programs\Python\Python39\lib\importlib\_bootstrap.py in _find_and_load(name='napari_nd_annotator', import_=)

~\AppData\Local\Programs\Python\Python39\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name='napari_nd_annotator', import_=)

~\AppData\Local\Programs\Python\Python39\lib\importlib\_bootstrap.py in _load_unlocked(spec=ModuleSpec(name='napari_nd_annotator', loader=

~\AppData\Local\Programs\Python\Python39\lib\importlib\_bootstrap_external.py in exec_module(self=, module=)

~\AppData\Local\Programs\Python\Python39\lib\importlib\_bootstrap.py in _call_with_frames_removed(f=, *args=( at 0x000001534D85A0E0, fil...ackages\napari_nd_annotator\__init__.py", line 2>, {'__builtins__': {'ArithmeticError': , 'AssertionError': , 'AttributeError': , 'BaseException': , 'BlockingIOError': , 'BrokenPipeError': , 'BufferError': , 'BytesWarning': , 'ChildProcessError': , 'ConnectionAbortedError': , ...}, '__cached__': r'C:\Users\Cochlear\AppData\Local\Programs\Python\..._nd_annotator\__pycache__\__init__.cpython-39.pyc', '__doc__': None, '__file__': r'C:\Users\Cochlear\AppData\Local\Programs\Python\...lib\site-packages\napari_nd_annotator\__init__.py', '__loader__': , '__name__': 'napari_nd_annotator', '__package__': 'napari_nd_annotator', '__path__': [r'C:\Users\Cochlear\AppData\Local\Programs\Python\Python39\lib\site-packages\napari_nd_annotator'], '__spec__': ModuleSpec(name='napari_nd_annotator', loader=

~\AppData\Local\Programs\Python\Python39\lib\site-packages\napari_nd_annotator\__init__.py in 
      3 
----> 4 from ._widgets import AnnotatorWidget, InterpolationWidget, ListWidgetBB
        global _widgets = undefined
        global AnnotatorWidget = undefined
        global InterpolationWidget = undefined
        global ListWidgetBB = undefined

~\AppData\Local\Programs\Python\Python39\lib\site-packages\napari_nd_annotator\_widgets\__init__.py in 
----> 1 from .interpolation_widget import InterpolationWidget
        global interpolation_widget = undefined
        global InterpolationWidget = undefined
      2 from .object_list import ListWidgetBB
      3 from .projections import SliceDisplayWidget

~\AppData\Local\Programs\Python\Python39\lib\site-packages\napari_nd_annotator\_widgets\interpolation_widget.py in 
     13 from ._utils.progress_widget import ProgressWidget
---> 14 from ..mean_contour import settings
        global mean_contour = undefined
        global settings = undefined
     15 from ..mean_contour.meanContour import MeanThread

~\AppData\Local\Programs\Python\Python39\lib\site-packages\napari_nd_annotator\mean_contour\settings.py in 
      1 import json
----> 2 from .util import getReconMethod
        global util = undefined
        global getReconMethod = undefined
      3 

~\AppData\Local\Programs\Python\Python39\lib\site-packages\napari_nd_annotator\mean_contour\util.py in 
      1 import numpy as np
----> 2 from ._essentials import ReconstructionMethods, Contour
        global _essentials = undefined
        global ReconstructionMethods = undefined
        global Contour = undefined
      3 import matplotlib.pyplot as plt

src\napari_nd_annotator\mean_contour\cEssentialscy.pyx in init napari_nd_annotator.mean_contour._essentials()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Programs\Python\Python39\lib\site-packages\napari\_qt\menus\plugins_menu.py in _add_toggle_widget(key=('napari-nD-annotator', 'Object List'), hook_type='dock')
     95 
     96                 if hook_type == 'dock':
---> 97                     dock_widget, _w = self._win.add_plugin_dock_widget(*key)
        dock_widget = undefined
        _w = undefined
        global self._win.add_plugin_dock_widget = undefined
        key = ('napari-nD-annotator', 'Object List')
     98                 else:
     99                     dock_widget = self._win._add_plugin_function_widget(*key)

~\AppData\Local\Programs\Python\Python39\lib\site-packages\napari\_qt\qt_main_window.py in add_plugin_dock_widget(self=, plugin_name='napari-nD-annotator', widget_name='Object List')
    662         dock_kwargs = {}
    663 
--> 664         result = _npe2.get_widget_contribution(plugin_name, widget_name)
        result = undefined
        _npe2.get_widget_contribution = 
        plugin_name = 'napari-nD-annotator'
        widget_name = 'Object List'
    665         if result:
    666             Widget, widget_name = result

~\AppData\Local\Programs\Python\Python39\lib\site-packages\napari\plugins\_npe2.py in get_widget_contribution(plugin_name='napari-nD-annotator', widget_name='Object List')
    106         if contrib.plugin_name == plugin_name:
    107             if not widget_name or contrib.display_name == widget_name:
--> 108                 return contrib.get_callable(), contrib.display_name
        contrib.get_callable = 
        contrib.display_name = 'Object List'
    109             widgets_seen.add(contrib.display_name)
    110     if widget_name and widgets_seen:

~\AppData\Local\Programs\Python\Python39\lib\site-packages\npe2\manifest\widgets.py in get_callable(self=WidgetContribution(command='napari-nD-annotator...., display_name='Object List', autogenerate=False), _registry=None)
     48         self, _registry: Optional[CommandRegistry] = None
     49     ) -> Callable[..., Widget]:
---> 50         func = super().get_callable()
        func = undefined
        global super.get_callable = undefined
     51         if self.autogenerate:
     52             from magicgui import magic_factory

~\AppData\Local\Programs\Python\Python39\lib\site-packages\npe2\manifest\utils.py in get_callable(self=WidgetContribution(command='napari-nD-annotator...., display_name='Object List', autogenerate=False), _registry=)
     54 
     55             _registry = PluginManager.instance().commands
---> 56         return _registry.get(self.command)
        _registry.get = >
        self.command = 'napari-nD-annotator.object_list_widget'
     57 
     58     @property

~\AppData\Local\Programs\Python\Python39\lib\site-packages\npe2\_command_registry.py in get(self=, id='napari-nD-annotator.object_list_widget')
    110             if id not in self._commands:
    111                 raise KeyError(f"command {id!r} not registered")
--> 112         return self._commands[id].resolve()
        self._commands = {'napari-nD-annotator.annotator_widget': CommandHandler(id='napari-nD-annotator.annotator_widget', function=None, python_name='napari_nd_annotator:AnnotatorWidget'), 'napari-nD-annotator.interpolation_widget': CommandHandler(id='napari-nD-annotator.interpolation_widget', function=None, python_name='napari_nd_annotator:InterpolationWidget'), 'napari-nD-annotator.object_list_widget': CommandHandler(id='napari-nD-annotator.object_list_widget', function=None, python_name='napari_nd_annotator:ListWidgetBB')}
        id.resolve = undefined
    113 
    114     def execute(self, id: str, args=(), kwargs={}) -> Any:

~\AppData\Local\Programs\Python\Python39\lib\site-packages\npe2\_command_registry.py in resolve(self=CommandHandler(id='napari-nD-annotator.object_li..., python_name='napari_nd_annotator:ListWidgetBB'))
     30             self.function = import_python_name(self.python_name)
     31         except Exception as e:
---> 32             raise RuntimeError(f"Failed to import command at {self.python_name!r}: {e}")
        global RuntimeError = undefined
     33         return self.function
     34 

RuntimeError: Failed to import command at 'napari_nd_annotator:ListWidgetBB': numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
**Screenshots**

**napari info**

**Other packages**
napari: 0.4.15
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9664
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.6
- scikit-image: 0.4.15
- svg: 0.1.6

pip v 22.2.2

**Comment by bauerdavid** [comment]
Try updating the numpy version, I think that might be the issue.
