### ISSUE TITLE
Package is using `PyQt5` imports instead of `qtpy`

### ISSUE THREAD

**Issue by goanpeca** [bauerdavid/napari-nD-annotator#39]
Hello team!

The plugin documentation for napari has a set of best practices for developers, which includes a clause recommending not to depend directly on PyQt5 or PySide2 to allow end-users to choose their bindings freely. [More details here](https://napari.org/stable/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies).

The files using `PyQt5` instead of `qtpy` -> https://github.com/bauerdavid/napari-nD-annotator/search?q=pyqt5

Is there a reason you need PyQt5 explicitly? Could these imports be updated to use `qtpy` for the next release?

Thanks!

**Comment by bauerdavid** [comment]
This is an error indeed, `qtpy` should be used. Thanks for pointing that out! Fixed in 128cd09b38afce3e041694aa12554f9596eaf1c0.

**Comment by goanpeca** [comment]
Thanks for the fix! :)
