### ISSUE TITLE
Provide in documentation information about pinned napari-version

### ISSUE THREAD

**Issue by marabuuu** [bauerdavid/napari-nD-annotator#42]
Hi  @bauerdavid, 

I really enjoy working with your plugin! But I struggled in the beginning with the installation, because I can not find in your documentation the hint that the napari-version was pinned to `napari == 0.4.15`  (partly connected to issue #32). 

And because I did not know that, I tried to install the plugin first in the following way:

```
mamba install napari=0.4.17 -c conda-forge
pip install napari-nD-annotator
```

which did lead to the following error message:

```
C:\Users\maral\mambaforge\envs\annotator_env\lib\site-packages\napari_nd_annotator\boundingbox\bounding_boxes.py:1549: RuntimeWarning: invalid value encountered in cast!
```
And this does not really help to come to the conclusion that you need to install the plugin like this:
```
mamba install napari=0.4.15 -c conda-forge
pip install napari-nD-annotator
```

where everything worked fine for me. So my recommendation would be to specify the pinned dependencies also in the documentation.

Thanks!

Best,
Mara

**Comment by bauerdavid** [comment]
Hey @marabuuu,
I'm sorry for your inconvenience! For now I included it in the Known Issues section of the readme (see 59993d5). For the next release we will check which napari versions are supported (now it should be fine with `0.4.15` and `0.4.16`).

Thanks for your feedback!

David
