### ISSUE TITLE
ModuleNotFoundError: No module named 'napari_nd_annotator.boundingbox'

### ISSUE THREAD

**Issue by Mdanishnadeem** [bauerdavid/napari-nD-annotator#47]
When I try to import the following 

from napari_nd_annotator.boundingbox import BoundingBoxLayer

I get the issue 
ModuleNotFoundError: No module named 'napari_nd_annotator.boundingbox'

even though I have installed napari_bbox as well

**Comment by bauerdavid** [comment]
Hey @Mdanishnadeem,
as you correctly noticed, the `BoundingBoxLayer` was moved to the `napari_bbox` plugin. You can import it as follows:
```
from napari_bbox import BoundingBoxLayer
```
