### ISSUE TITLE
Feature: pypi wheels for macOS arm64

### ISSUE THREAD

**Issue by psobolewskiPhD** [bauerdavid/napari-nD-annotator#53]
**Is your feature request related to a problem? Please describe.**

Installing on macOS arm64 (M1, M2) doesn't work, because there are no wheels on pypi and no up-to-date conda-forge package.

**Describe the solution you'd like**

use cibuildwheel to also build macOS arm64 wheels to upload to pypi.
Update conda-forge by merging: https://github.com/conda-forge/napari-nd-annotator-feedstock/pulls
And then have the bot make an arm64 PR.

**Describe alternatives you've considered**

I tried building from source but get an error:
`src/napari_nd_annotator/minimal_contour/_eikonal_wrapper.cpp:1273:10: fatal error: 'omp.h' file not found`
Maybe some build-from-source documentation could be provided if wheels are not feasible?

**Comment by bauerdavid** [comment]
Thanks for raising this issue! I included macOS to be built with cibuildwheel, but I don't know how to add arm64 to the list. I'll check it soon.
Regarding the error, unfortunately I don't have access to a mac, so I can't test what setup is required on macOS. If you could help me with that, it would be super useful.

**Comment by psobolewskiPhD** [comment]
Looking at your workflow and the error it's likely due to my not having or having a differently configed libomp.
I won't have time in the near future to try to sort it out locally.
However, I think it should be simple to get your workflow to build arm64, so I will give that a shot!
